Proyecto1BasesDeDatos1/TiendaRepuestosAuto_BD1 WEB/Models/Persona.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TiendaRepuestosAuto_BD1_WEB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Persona
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Persona()
        {
            this.Telefono = new HashSet<Telefono>();
        }
    
        public int Cedula { get; set; }
        public string nombre { get; set; }
        public int ID_ClientePersona { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Telefono> Telefono { get; set; }
    }
}

Proyecto1BasesDeDatos1/TiendaRepuestosAuto_BD1 WEB/Controllers/PersonasController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Data.Entity.Core.Objects;
using System.Data.Entity.Infrastructure;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using TiendaRepuestosAuto_BD1_WEB.Models;
using TiendaRepuestosAuto_BD1_WEB.Models.DataBaseModelForApp;

namespace TiendaRepuestosAuto_BD1_WEB.Controllers
{
    public class PersonasController : Controller
    {
        private TiendaRepuestosAuto_BD1Entities5 db = new TiendaRepuestosAuto_BD1Entities5();

        // GET: Personas
        public ActionResult Index(string Nombre, int? Cedula)
        {
            var personas = db.Persona.Include(p => p.Cliente).Where((p => p.nombre.StartsWith(Nombre) || Nombre == null)).Where(p => p.Cedula.ToString().StartsWith(Cedula.ToString()) || Cedula == null);
            return View(personas.ToList());
        }

        // GET: Personas/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Persona persona = db.Persona.Find(id);
            List<Telefono> telefonosL = db.Telefono.Where(t => t.Cedula == id).ToList();

            personaModel personaModel = new personaModel
            {
                Cedula = persona.Cedula,
                nombre = persona.nombre,
                Ciudad = persona.Cliente.Ciudad,
                Direccion = persona.Cliente.Direccion,
                telefonos = telefonosL,
                ID_Cliente = persona.Cliente.ID_Cliente,
                Estado = persona.Cliente.EstadoDeCliente.Tipo
            };
            if (persona == null)
            {
                return HttpNotFound();
            }
            return View(personaModel);
        }

        // GET: Personas/Create
        public ActionResult Create()
        {
            ViewBag.ID_ClientePersona = new SelectList(db.Cliente, "ID_Cliente", "Direccion");
            ViewBag.ID_EstadoDeCliente = new SelectList(db.EstadoDeCliente, "ID_EstadoDeCliente", "Tipo");
            return View();
        }

        // POST: Personas/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Cliente cliente, Persona persona, Telefono telefono)
        {
            if (ModelState.IsValid )
            {
                /*
                db.Clientes.Add(cliente);
                db.SaveChanges();
                persona.ID_ClientePersona = cliente.ID_Cliente;
                db.spAddPersonaOnly(persona.Cedula, persona.nombre, persona.ID_ClientePersona);
                */
                //string result1 = "";
                ObjectParameter result = new ObjectParameter("OpReturn",typeof(string));
                db.spAddClienteAndPersona2(persona.Cedula, persona.nombre, cliente.Direccion, cliente.Ciudad, 0, result);
                System.Diagnostics.Debug.WriteLine(result.ToString());
                if(db.Persona.Find(persona.Cedula) != null)
                {
                    telefono.Cedula = persona.Cedula;
                    db.Telefono.Add(telefono);
                    db.SaveChanges();
                }
                personaModel personaModel = new personaModel
                {
                    Cedula = persona.Cedula,
                    nombre = persona.nombre,
                    Direccion = cliente.Direccion,
                    Ciudad = cliente.Ciudad,
                    ID_EstadoDeCliente = cliente.ID_EstadoDeCliente,
                    NumeroDeTelefono = telefono.NumeroDeTelefono
                };

                if (result.Value.ToString() == "Record Inserted Successfully")
                {
                    ViewBag.Resultado = true;
                }
                else
                {
                    ViewBag.Resultado = false;
                }

                ViewBag.Message = result.Value.ToString();
                ViewBag.ID_EstadoDeCliente = new SelectList(db.EstadoDeCliente, "ID_EstadoDeCliente", "Tipo");
                return View(personaModel);
            }
            else
            {
                return RedirectToAction("Index");
            }

            //ViewBag.ID_ClientePersona = new SelectList(db.Clientes, "ID_Cliente", "Direccion", persona.ID_ClientePersona);
        }

        // GET: Personas/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Persona persona = db.Persona.Find(id);
            if (persona == null)
            {
                return HttpNotFound();
            }
            ViewBag.ID_EstadoDeCliente = new SelectList(db.EstadoDeCliente, "ID_EstadoDeCliente", "Tipo", persona.Cliente.ID_EstadoDeCliente);
            personaModel personaModel = new personaModel
            {
                Cedula = persona.Cedula,
                nombre = persona.nombre,
                Ciudad = persona.Cliente.Ciudad,
                Direccion = persona.Cliente.Direccion,
                ID_EstadoDeCliente = persona.Cliente.ID_EstadoDeCliente,
                ID_Cliente = persona.Cliente.ID_Cliente,
                Estado = persona.Cliente.EstadoDeCliente.Tipo
            };
            return View(personaModel);
        }

        // POST: Personas/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(personaModel personaModel)
        {
            if (ModelState.IsValid)
            {
                db.spModifyPersona(personaModel.Cedula, personaModel.nombre, personaModel.Direccion, personaModel.Ciudad, personaModel.ID_EstadoDeCliente);
                //db.SaveChanges();
                return RedirectToAction("Index");
            }
            //ViewBag.ID_ClientePersona = new SelectList(db.Cliente, "ID_Cliente", "Direccion", persona.ID_ClientePersona);
            return View(personaModel);
        }

        // GET: Personas/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Persona persona = db.Persona.Find(id);
            if (persona == null)
            {
                return HttpNotFound();
            }
            return View(persona);
        }

        // POST: Personas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Persona persona = db.Persona.Find(id);
            db.Persona.Remove(persona);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        private bool isCedulaValida(int cedula)
        {
            var personas = db.Persona.Include(p => p.Cliente);
            personas.ToList();
            foreach (var item in personas)
            {
                if(item.Cedula == cedula)
                {
                    return false;
                }
            }
            return true;
        }

        public ActionResult suspenderPersona(int? id, int? Cedula)
        {
            db.spSuspenderPersona(id);
            if(Cedula != null)
            {
                Persona persona = db.Persona.Find(Cedula);
                return RedirectToAction("Edit", new { id = Cedula });
            }
            return RedirectToAction("Index");
        }

        public ActionResult activarPersona(int? id, int? Cedula)
        {
            db.spClienteSetActive(id);
            if (Cedula != null)
            {
                Persona persona = db.Persona.Find(Cedula);
                return RedirectToAction("Edit", new { id = Cedula });
            }
            return RedirectToAction("Index");

        }

        public ActionResult desactivarPersona(int? id, int? Cedula)
        {
            db.spClienteSetInactive(id);
            if (Cedula != null)
            {
                Persona persona = db.Persona.Find(Cedula);
                return RedirectToAction("Edit", new { id = Cedula });
            }
            return RedirectToAction("Index");
        }
    }
}

Proyecto1BasesDeDatos1/TiendaRepuestosAuto_BD1 WEB/Views/Personas/Create.cshtml
@model TiendaRepuestosAuto_BD1_WEB.Models.DataBaseModelForApp.personaModel

@{
    ViewBag.Title = "Create";
}

<h2>Crear</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Persona</h4>
        <hr />

        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Cedula, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Cedula, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Cedula, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.nombre, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.nombre, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.nombre, "", new { @class = "text-danger" })
            </div>
        </div>

        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Direccion, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Direccion, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Direccion, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Ciudad, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Ciudad, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Ciudad, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NumeroDeTelefono, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NumeroDeTelefono, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NumeroDeTelefono, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
    if (ViewBag.Message != null)
    {
        bool result = ViewBag.Resultado;

        if (result)
        {
            <script type="text/javascript">
            window.onload = function () {
                alert("@ViewBag.Message");
                window.location.href = "/Organizacion/Index"
            }
            </script>
        }
        else
        {
            <script type="text/javascript">
            window.onload = function () {
                alert("@ViewBag.Message");
            }
            </script>
        }
    }
}

<div>
    @Html.ActionLink("Regresar a lista", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Proyecto1BasesDeDatos1/TiendaRepuestosAuto_BD1 WEB/Views/Personas/Delete.cshtml
@model TiendaRepuestosAuto_BD1_WEB.Models.Persona

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Persona</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.nombre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Cliente.Direccion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Cliente.Direccion)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Proyecto1BasesDeDatos1/TiendaRepuestosAuto_BD1 WEB/Views/Personas/Details.cshtml
@model TiendaRepuestosAuto_BD1_WEB.Models.DataBaseModelForApp.personaModel

@{
    ViewBag.Title = "Details";
}

<h2>Detalles</h2>

<div>
    <h4>Persona</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Cedula)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Cedula)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.nombre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Ciudad)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Ciudad)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Direccion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Direccion)
        </dd>

        <dt>
            @Html.DisplayName("Estado")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Estado)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Regresar a lista", "Index") |
    @Html.ActionLink("Modificar", "Edit", new { id = Model.Cedula }) |
    @Html.ActionLink("Agregar Telefono", "Create", new { controller = "Telefonoes", Cedula = Model.Cedula, nombre = Model.nombre })
</p>


<table class="table">
    <tr>
        <th>
            @Html.DisplayName("Números de telfono")
        </th>
    </tr>

    @foreach (var item in Model.telefonos)
    {

        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.NumeroDeTelefono)
            </td>
            <td>
                @Html.ActionLink("Modificar", "Edit", new { controller = "Telefonoes", id = item.ID_Telefono, Nombre = Model.nombre })
            </td>
        </tr>
    }
</table>

Proyecto1BasesDeDatos1/TiendaRepuestosAuto_BD1 WEB/Views/Personas/Edit.cshtml
@model TiendaRepuestosAuto_BD1_WEB.Models.DataBaseModelForApp.personaModel

@{
    ViewBag.Title = "Edit";
}

<h2>Modificar</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Persona</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Cedula)
        @Html.HiddenFor(model => model.ID_EstadoDeCliente)
        <div class="form-group">
            @Html.LabelFor(model => model.Cedula, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DisplayFor(model => model.Cedula, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Cedula, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.nombre, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.nombre, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.nombre, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Ciudad, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Ciudad, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Ciudad, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Direccion, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Direccion, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Direccion, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Estado, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DisplayFor(model => model.Estado, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Estado, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Regresar a lista", "Index") |
    @Html.ActionLink("Agregar Telefono", "Create", new { controller = "Telefonoes", Cedula = Model.Cedula, nombre = Model.nombre }) |
    @Html.ActionLink("Activar", "activarPersona", new { id = Model.ID_Cliente, Cedula = Model.Cedula }) |
    @Html.ActionLink("Desactivar", "desactivarPersona", new { id = Model.ID_Cliente, Cedula = Model.Cedula }) |
    @Html.ActionLink("Suspender", "suspenderPersona", new { id = Model.Cedula, Cedula = Model.Cedula })
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Proyecto1BasesDeDatos1/TiendaRepuestosAuto_BD1 WEB/Views/Personas/Index.cshtml
@model IEnumerable<TiendaRepuestosAuto_BD1_WEB.Models.Persona>

@{
    ViewBag.Title = "Index";
}

<h2>Lista</h2>

<p>
    @Html.ActionLink("Crear nueva persona", "Create")
</p>

<p>
    @using (Html.BeginForm("Index", "Personas", FormMethod.Get))
    {
        <style>
            label {
                text-align: left;
                width: 100px;
                display: block;
                float: left;
                clear: right;
                font-size: 18;
            }

        </style>

        <b>Buscar personas</b><br /><br />
        <label for="Nombre"> Nombre: </label>
        <input type="text" id="Nombre" name="Nombre"><br>
        <label for="Cedula"> Cedula: </label>
        <input type="number" id="Cedula" name="Cedula"><br>
        <input type="submit" value="Buscar">
    }
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayName("Cedula")
        </th>
        <th>
            @Html.DisplayName("Nombre Completo")
        </th>
        <th>
            @Html.DisplayName("Ciudad")
        </th>
        <th>
            @Html.DisplayName("Dirección")
        </th>
        <th>
            @Html.DisplayName("Estado")
        </th>
        <th></th>
        <th>@Html.DisplayName("Opciones")</th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Cedula)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.nombre)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Cliente.Ciudad)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Cliente.Direccion)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Cliente.EstadoDeCliente.Tipo)
        </td>
        <td>
            @Html.ActionLink("Modificar", "Edit", new { id = item.Cedula })       |
        </td>
        <td>
            @Html.ActionLink("Detalles", "Details", new { id = item.Cedula })       |
        </td>
        <td>
            @Html.ActionLink("Activar", "activarPersona", new { id = item.Cliente.ID_Cliente }) |
            @Html.ActionLink("Desactivar", "desactivarPersona", new { id = item.Cliente.ID_Cliente }) |
            @Html.ActionLink("Suspender", "suspenderPersona", new { id = item.Cedula })
        </td>
    </tr>
}

</table>