Proyecto1BasesDeDatos1/TiendaRepuestosAuto_BD1 WEB/Models/Organizacion.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TiendaRepuestosAuto_BD1_WEB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Organizacion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Organizacion()
        {
            this.Contacto1 = new HashSet<Contacto>();
        }
    
        public long CedulaJuridica { get; set; }
        public string Nombre { get; set; }
        public int ID_Cliente { get; set; }
        public Nullable<int> ID_Contacto { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual Contacto Contacto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Contacto> Contacto1 { get; set; }
    }
}

Proyecto1BasesDeDatos1/TiendaRepuestosAuto_BD1 WEB/Controllers/OrganizacionController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Data.Entity.Core.Objects;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using TiendaRepuestosAuto_BD1_WEB.Models;
using TiendaRepuestosAuto_BD1_WEB.Models.DataBaseModelForApp;

namespace TiendaRepuestosAuto_BD1_WEB.Controllers
{
    public class OrganizacionController : Controller
    {
        private TiendaRepuestosAuto_BD1Entities5 db = new TiendaRepuestosAuto_BD1Entities5();

        // GET: Organizacion
        public ActionResult Index(string Nombre, long? CedulaJuridica)
        {
            var organizacions = db.Organizacion.Include(o => o.Cliente).Include(o => o.Contacto).Where(o => o.Nombre.StartsWith(Nombre) || Nombre == null).Where(o => o.CedulaJuridica.ToString().StartsWith(CedulaJuridica.ToString()) || CedulaJuridica == null);
            return View(organizacions.ToList());
        }

        // GET: Organizacion/Details/5
        public ActionResult Details(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Organizacion organizacion = db.Organizacion.Find(id);
            if (organizacion == null)
            {
                return HttpNotFound();
            }
            return View(organizacion);
        }

        // GET: Organizacion/Create
        public ActionResult Create()
        {
            ViewBag.ID_EstadoDeCliente = new SelectList(db.EstadoDeCliente, "ID_EstadoDeCliente", "Tipo");
            ViewBag.ID_Cliente = new SelectList(db.Cliente, "ID_Cliente", "Direccion");
            ViewBag.ID_Contacto = new SelectList(db.Contacto, "ID_Contacto", "Nombre");
            return View();
        }

        // POST: Organizacion/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Cliente cliente, Organizacion organizacion, Contacto contacto)
        {
            if (ModelState.IsValid)
            {
                ObjectParameter result = new ObjectParameter("opReturn", typeof(string));
                db.spAddClienteAndOrganizacion2(organizacion.CedulaJuridica, organizacion.Nombre, cliente.Direccion, cliente.Ciudad, 0, contacto.Nombre, contacto.Telefono, contacto.Cargo, result);
                
                OrganizacionModel organizacionModel = new OrganizacionModel
                {
                    CedulaJuridica = organizacion.CedulaJuridica,
                    Nombre = organizacion.Nombre,
                    Direccion = cliente.Direccion,
                    Ciudad = cliente.Ciudad,
                    ID_EstadoDeCliente = cliente.ID_EstadoDeCliente,
                    Contacto = new ContactoModel
                    {
                        Telefono = contacto.Telefono,
                        Cargo = contacto.Cargo,
                        Nombre = contacto.Nombre
                    }

                };

                if (result.Value.ToString() == "Record Inserted Successfully")
                {
                    ViewBag.Resultado = true;
                }
                else
                {
                    ViewBag.Resultado = false;
                }

                ViewBag.Message = result.Value.ToString();
                ViewBag.ID_EstadoDeCliente = new SelectList(db.EstadoDeCliente, "ID_EstadoDeCliente", "Tipo");
                return View(organizacionModel);

            }

            ViewBag.ID_Cliente = new SelectList(db.Cliente, "ID_Cliente", "Direccion", organizacion.ID_Cliente);
            ViewBag.ID_Contacto = new SelectList(db.Contacto, "ID_Contacto", "Nombre", organizacion.ID_Contacto);
            return View(organizacion);
        }

        // GET: Organizacion/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Organizacion organizacion = db.Organizacion.Find(id);
            if (organizacion == null)
            {
                return HttpNotFound();
            }
            ViewBag.ID_EstadoDeCliente = new SelectList(db.EstadoDeCliente, "ID_EstadoDeCliente", "Tipo", organizacion.Cliente.ID_EstadoDeCliente);

            OrganizacionModel organizacionModel = new OrganizacionModel
            {
                CedulaJuridica = organizacion.CedulaJuridica,
                Nombre = organizacion.Nombre,
                Ciudad = organizacion.Cliente.Ciudad,
                Direccion = organizacion.Cliente.Direccion,
                ID_EstadoDeCliente = organizacion.Cliente.ID_EstadoDeCliente,
                ID_Cliente = organizacion.Cliente.ID_Cliente,
                Estado = organizacion.Cliente.EstadoDeCliente.Tipo,
                Contacto = new ContactoModel
                {
                    Nombre = organizacion.Contacto.Nombre,
                    Telefono = organizacion.Contacto.Telefono,
                    Cargo = organizacion.Contacto.Cargo
                }
            };

            ViewBag.ID_Cliente = new SelectList(db.Cliente, "ID_Cliente", "Direccion", organizacion.ID_Cliente);
            ViewBag.ID_Contacto = new SelectList(db.Contacto, "ID_Contacto", "Nombre", organizacion.ID_Contacto);
            return View(organizacionModel);
        }

        // POST: Organizacion/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(OrganizacionModel organizacion)
        {
            if (ModelState.IsValid)
            {
                db.spModifyOrganizacion2(organizacion.CedulaJuridica,organizacion.Nombre,organizacion.Direccion,organizacion.Ciudad,organizacion.ID_EstadoDeCliente,organizacion.Contacto.Nombre,organizacion.Contacto.Telefono,organizacion.Contacto.Cargo);
                return RedirectToAction("Index");
            }
            return View(organizacion);
        }

        // GET: Organizacion/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Organizacion organizacion = db.Organizacion.Find(id);
            if (organizacion == null)
            {
                return HttpNotFound();
            }
            return View(organizacion);
        }

        // POST: Organizacion/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Organizacion organizacion = db.Organizacion.Find(id);
            db.Organizacion.Remove(organizacion);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        public ActionResult suspenderOrganizacion(long? id, long? CedulaJuridica)
        {
            db.spSuspenderOrganizacion2(id);
            if (CedulaJuridica != null)
            {
                return RedirectToAction("Edit", new { id = CedulaJuridica });
            }
            return RedirectToAction("Index");
        }

        public ActionResult activarOrganizacion(int? id, long? CedulaJuridica)
        {
            db.spClienteSetActive(id);
            if (CedulaJuridica != null)
            {
                return RedirectToAction("Edit", new { id = CedulaJuridica });
            }
            return RedirectToAction("Index");

        }

        public ActionResult desactivarOrganizacion(int? id, long? CedulaJuridica)
        {
            db.spClienteSetInactive(id);
            if (CedulaJuridica != null)
            {
                return RedirectToAction("Edit", new { id = CedulaJuridica });
            }
            return RedirectToAction("Index");
        }
    }
}

Proyecto1BasesDeDatos1/TiendaRepuestosAuto_BD1 WEB/Views/Organizacion/Create.cshtml
@model TiendaRepuestosAuto_BD1_WEB.Models.DataBaseModelForApp.OrganizacionModel

@{
    ViewBag.Title = "Create";
}

<h2>Crear</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Organizacion</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.CedulaJuridica, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CedulaJuridica, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CedulaJuridica, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Nombre, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })
            </div>
        </div>

        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Direccion, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Direccion, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Direccion, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Ciudad, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Ciudad, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Ciudad, "", new { @class = "text-danger" })
            </div>
        </div>

        <h4>Contacto</h4>
        <hr />
        <div class="form-group">
            @Html.LabelFor(model => model.Contacto.Nombre, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Contacto.Nombre, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Contacto.Nombre, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Contacto.Telefono, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Contacto.Telefono, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Contacto.Telefono, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Contacto.Cargo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Contacto.Cargo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Contacto.Cargo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
    if (ViewBag.Message != null)
    {
        bool result = ViewBag.Resultado;

        if (result)
        {
            <script type="text/javascript">
            window.onload = function () {
                alert("@ViewBag.Message");
                window.location.href = "/Organizacion/Index"
            }
            </script>
        }
        else
        {
            <script type="text/javascript">
            window.onload = function () {
                alert("@ViewBag.Message");
            }
            </script>
        }
    }
}

<div>
    @Html.ActionLink("Regresar a lista", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Proyecto1BasesDeDatos1/TiendaRepuestosAuto_BD1 WEB/Views/Organizacion/Delete.cshtml
@model TiendaRepuestosAuto_BD1_WEB.Models.Organizacion

@{
    ViewBag.Title = "Delete";
}

<h2>Borrar</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Organizacion</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nombre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Cliente.Direccion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Cliente.Direccion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Contacto.Nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Contacto.Nombre)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Regresar a lista", "Index")
        </div>
    }
</div>

Proyecto1BasesDeDatos1/TiendaRepuestosAuto_BD1 WEB/Views/Organizacion/Details.cshtml
@model TiendaRepuestosAuto_BD1_WEB.Models.Organizacion

@{
    ViewBag.Title = "Details";
}

<h2>Detalles</h2>

<div>
    <h4>Organizacion</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayName("Cedula Juridica")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CedulaJuridica)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nombre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Cliente.Ciudad)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Cliente.Ciudad)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Cliente.Direccion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Cliente.Direccion)
        </dd>

        <dt>
            @Html.DisplayName("Estado")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Cliente.EstadoDeCliente.Tipo)
        </dd>
    </dl>
    <dl class="dl-horizontal">
        <h4>Contacto</h4>
        <hr />
        <dt>
            @Html.DisplayNameFor(model => model.Contacto.Nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Contacto.Nombre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Contacto.Cargo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Contacto.Cargo)
        </dd>

        <dt>
            @Html.DisplayName("Telefono")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Contacto.Telefono)
        </dd>
    </dl>
</div>
<p>
    @Html.ActionLink("Modificar", "Edit", new { id = Model.CedulaJuridica }) |
    @Html.ActionLink("Regresar a lista", "Index")
</p>

Proyecto1BasesDeDatos1/TiendaRepuestosAuto_BD1 WEB/Views/Organizacion/Edit.cshtml
@model TiendaRepuestosAuto_BD1_WEB.Models.DataBaseModelForApp.OrganizacionModel

@{
    ViewBag.Title = "Edit";
}

<h2>Modificar</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4>Organizacion</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.CedulaJuridica)
    @Html.HiddenFor(model => model.ID_EstadoDeCliente)

    <div class="form-group">
        @Html.LabelFor(model => model.CedulaJuridica, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DisplayFor(model => model.CedulaJuridica, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.CedulaJuridica, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Nombre, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Ciudad, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Ciudad, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Ciudad, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Direccion, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Direccion, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Direccion, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Estado, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DisplayFor(model => model.Estado, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Estado, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Contacto.Nombre, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Contacto.Nombre, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Contacto.Nombre, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Contacto.Telefono, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Contacto.Telefono, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Contacto.Telefono, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Contacto.Cargo, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Contacto.Cargo, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Contacto.Cargo, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Save" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Regresar a lista", "Index") |
    @Html.ActionLink("Activar", "activarOrganizacion", new { id = Model.ID_Cliente, CedulaJuridica = Model.CedulaJuridica }) |
    @Html.ActionLink("Desactivar", "desactivarOrganizacion", new { id = Model.ID_Cliente, CedulaJuridica = Model.CedulaJuridica }) |
    @Html.ActionLink("Suspender", "suspenderOrganizacion", new { id = Model.CedulaJuridica, CedulaJuridica = Model.CedulaJuridica })
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Proyecto1BasesDeDatos1/TiendaRepuestosAuto_BD1 WEB/Views/Organizacion/Index.cshtml
@model IEnumerable<TiendaRepuestosAuto_BD1_WEB.Models.Organizacion>

@{
    ViewBag.Title = "Index";
}

<h2>Lista</h2>

<p>
    @Html.ActionLink("Crear nueva organización", "Create")
</p>

<p>
    @using (Html.BeginForm("Index", "Organizacion", FormMethod.Get))
    {
        <style>
            label {
                text-align: left;
                width: 150px;
                display: block;
                float: left;
                clear: right;
                font-size: 18;
            }
        </style>

        <b>Buscar personas</b><br /><br />
        <label for="Nombre"> Nombre: </label>
        <input type="text" id="Nombre" name="Nombre"><br>
        <label for="CedulaJuridica"> Cedula Juridica: </label>
        <input type="number" id="CedulaJuridica" name="CedulaJuridica"><br>
        <input type="submit" value="Buscar">
    }
</p>

<table class="table">
    <tr>
        <th>
            @Html.DisplayName("Cédula jurídica")
        </th>
        <th>
            @Html.DisplayName("Nombre de Organización")
        </th>
        <th>
            @Html.DisplayName("Ciudad")
        </th>
        <th>
            @Html.DisplayName("Dirección")
        </th>
        <th>
            @Html.DisplayName("Estado")
        </th>
        <th>
            @Html.DisplayName("Contacto")
        </th>
        <th>
            @Html.DisplayName("Telefono")
        </th>
        <th>
            @Html.DisplayName("Cargo")
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.CedulaJuridica)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Nombre)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Cliente.Ciudad)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Cliente.Direccion)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Cliente.EstadoDeCliente.Tipo)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Contacto.Nombre)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Contacto.Telefono)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Contacto.Cargo)
        </td>
        <td>
            @Html.ActionLink("Modificar", "Edit", new { id = item.CedulaJuridica }) |
            @Html.ActionLink("Detalles", "Details", new { id = item.CedulaJuridica }) |
            @Html.ActionLink("Activar", "activarOrganizacion", new { id = item.Cliente.ID_Cliente }) |
            @Html.ActionLink("Desactivar", "desactivarOrganizacion", new { id = item.Cliente.ID_Cliente }) | 
            @Html.ActionLink("Suspender", "suspenderOrganizacion", new { id = item.CedulaJuridica })
        </td>
    </tr>
}

</table>